#spring.application.name=libreria
## configuracion de conexión
#spring.datasource.url=jdbc:mysql://localhost:3306/dblibreriacarrito?useSSL=false&serverTimezone=UTC
#spring.datasource.username= "root"
#spring.datasource.password= "root"
#
## dialecto de MySQL
## spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## Esquema
#spring.jpa.hibernate.ddl-auto=update
#
##mostrar en consola
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.application.name=libreria

# configuracion de conexion hacia BD
spring.datasource.url=jdbc:mysql://localhost:3306/dblibreriacarrito?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# esquema
spring.jpa.hibernate.ddl-auto=update

#Dialecto de Mysql
#spring.jpa.database.platform=org.hibernate.dialect.MySQL8Dialect

#mostrar por consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver